setting:
  lbsKey: "KN6BZ-G526D-JAI4V-PGSJ2-6L5U6-YYFBV"
  offset: 6  #直线距离计算偏移量，单位米
  avoidAreaOffset: 0.000100 #生成四边形避让区偏移量, 单位经纬度
  maxAvoid: 32 # 最大避让区
  maxRoute: 15 # 最大路线规划次数
  towardRange: 70 # 路段朝向角度与探头的朝向角度值差，如果小于towardRange则认为是同一个方向

probeManager:
  probes:
    - lat: 22.57682
      lon: 113.913137
      towards: # 探头朝向的坐标，有可能多个
        - lat: 22.576917
          lon: 113.91323
    - lat: 22.57759
      lon: 113.914101
      towards: # 探头朝向的坐标，有可能多个
        - lat: 22.577651
          lon: 113.914054
        - lat: 22.577566
          lon: 113.914139
    - lat: 22.576349
      lon: 113.914133
    - lat: 22.576952
      lon: 113.914656
    - lat: 22.576974
      lon: 113.914728
