apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "driving-assistant.fullname" . }}-conf
  labels:
    {{- include "driving-assistant.labels" . | nindent 4 }}
data:
{{ (.Files.Glob "config.yaml").AsConfig | indent 2 }}
