apiVersion: v1
kind: Service
metadata:
  name: {{ include "driving-assistant.fullname" . }}
  labels:
    {{- include "driving-assistant.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.ports.http }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "driving-assistant.selectorLabels" . | nindent 4 }}
