// Package docs GENERATED BY SWAG; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/probes": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driving"
                ],
                "summary": "获取探头",
                "parameters": [
                    {
                        "type": "number",
                        "description": "当前位置经度",
                        "name": "lat",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "当前位置纬度",
                        "name": "lon",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "description": "获取附近多少公里的探头，0为获取所有探头",
                        "name": "near",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiserver.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apis.ProbeResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/api/route": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "driving"
                ],
                "summary": "路线规划，获取需要避让的区域",
                "parameters": [
                    {
                        "type": "number",
                        "name": "from_lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "name": "from_lon",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "name": "to_lat",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "number",
                        "name": "to_lon",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "返回结果",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/apiserver.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/apis.RouteResp"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "apis.Debug": {
            "type": "object",
            "properties": {
                "probe_count": {
                    "description": "需要避让的探头数量",
                    "type": "integer"
                },
                "route_count": {
                    "description": "路线规划次数",
                    "type": "integer"
                },
                "route_logs": {
                    "description": "路线规划日志",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/apis.DebugLog"
                    }
                }
            }
        },
        "apis.DebugLog": {
            "type": "object",
            "properties": {
                "cur_to_next_to_probe": {
                    "description": "本次计算后需要避让的探头，格式为：cur;next;probe (A1;A2;探头)",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "route_info": {
                    "description": "本次路线信息",
                    "type": "string"
                },
                "route_probe_info": {
                    "description": "本次路线信息传入的避让探头, 第一次传入的为空",
                    "type": "string"
                }
            }
        },
        "apis.ProbeResp": {
            "type": "object",
            "properties": {
                "probes": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/probe.Probe"
                    }
                }
            }
        },
        "apis.RouteResp": {
            "type": "object",
            "properties": {
                "avoidProbes": {
                    "description": "需要避让的探头",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/drive.Coord"
                    }
                },
                "avoid_areas": {
                    "description": "需要避让的区域",
                    "type": "array",
                    "items": {
                        "type": "array",
                        "items": {
                            "$ref": "#/definitions/drive.Coord"
                        }
                    }
                },
                "debug": {
                    "description": "debug信息",
                    "$ref": "#/definitions/apis.Debug"
                }
            }
        },
        "apiserver.Response": {
            "type": "object",
            "properties": {
                "data": {},
                "error": {
                    "type": "string"
                }
            }
        },
        "drive.Coord": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                }
            }
        },
        "probe.Probe": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "towards": {
                    "description": "探头朝向的坐标",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/probe.Toward"
                    }
                }
            }
        },
        "probe.Toward": {
            "type": "object",
            "properties": {
                "lat": {
                    "type": "number"
                },
                "lon": {
                    "type": "number"
                },
                "value": {
                    "description": "探头朝向的角度值",
                    "type": "number"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
