definitions:
  apis.Debug:
    properties:
      probe_count:
        description: 需要避让的探头数量
        type: integer
      route_count:
        description: 路线规划次数
        type: integer
      route_logs:
        description: 路线规划日志
        items:
          $ref: '#/definitions/apis.DebugLog'
        type: array
    type: object
  apis.DebugLog:
    properties:
      cur_to_next_to_probe:
        description: 本次计算后需要避让的探头，格式为：cur;next;probe (A1;A2;探头)
        items:
          type: string
        type: array
      route_info:
        description: 本次路线信息
        type: string
      route_probe_info:
        description: 本次路线信息传入的避让探头, 第一次传入的为空
        type: string
    type: object
  apis.ProbeResp:
    properties:
      probes:
        items:
          $ref: '#/definitions/probe.Probe'
        type: array
    type: object
  apis.RouteResp:
    properties:
      avoid_areas:
        description: 需要避让的区域
        items:
          items:
            $ref: '#/definitions/drive.Coord'
          type: array
        type: array
      avoidProbes:
        description: 需要避让的探头
        items:
          $ref: '#/definitions/drive.Coord'
        type: array
      debug:
        $ref: '#/definitions/apis.Debug'
        description: debug信息
    type: object
  apiserver.Response:
    properties:
      data: {}
      error:
        type: string
    type: object
  drive.Coord:
    properties:
      lat:
        type: number
      lon:
        type: number
    type: object
  probe.Probe:
    properties:
      lat:
        type: number
      lon:
        type: number
      towards:
        description: 探头朝向的坐标
        items:
          $ref: '#/definitions/probe.Toward'
        type: array
    type: object
  probe.Toward:
    properties:
      lat:
        type: number
      lon:
        type: number
      value:
        description: 探头朝向的角度值
        type: number
    type: object
info:
  contact: {}
paths:
  /api/probes:
    get:
      consumes:
      - application/json
      parameters:
      - description: 当前位置经度
        in: query
        name: lat
        type: number
      - description: 当前位置纬度
        in: query
        name: lon
        type: number
      - description: 获取附近多少公里的探头，0为获取所有探头
        in: query
        name: near
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            allOf:
            - $ref: '#/definitions/apiserver.Response'
            - properties:
                data:
                  $ref: '#/definitions/apis.ProbeResp'
              type: object
      summary: 获取探头
      tags:
      - driving
  /api/route:
    get:
      consumes:
      - application/json
      parameters:
      - in: query
        name: from_lat
        required: true
        type: number
      - in: query
        name: from_lon
        required: true
        type: number
      - in: query
        name: to_lat
        required: true
        type: number
      - in: query
        name: to_lon
        required: true
        type: number
      produces:
      - application/json
      responses:
        "200":
          description: 返回结果
          schema:
            allOf:
            - $ref: '#/definitions/apiserver.Response'
            - properties:
                data:
                  $ref: '#/definitions/apis.RouteResp'
              type: object
      summary: 路线规划，获取需要避让的区域
      tags:
      - driving
swagger: "2.0"
